
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ninja
      POSTGRES_PASSWORD: 1521
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ninja -d fastapi_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: python -m uvicorn FastAPI.main:app --host 0.0.0.0 --port 8000

    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  bot:
    build: .
    command: python -m Tg_bot.main
    depends_on:
      - api

volumes:
  postgres_data: